---
- name: Git checkout Bundle
  shell: > 
         cd "{{ target_dir }}"/pki && 
         mv bundle/dictionary.yml .. &&
         mv bundle .. &&
         mv tls/certs/web-infoclinica* ../bundle/certs &&
         mv tls/private/web-infoclinica* ../bundle/private &&
         rm -rf "{{ target_dir }}"/pki
